python main.py \
    --run_name analogical_multimem_within \
    --checkpoint analogical_multimem_within.pt \
    --checkpoint_path CHECKPOINT_PATH \
    --anno_path PATH_TO_PARTNET \
    --feat_path FEAT_PATH \
    --label_path PATH_TO_PARTNET_REPO/stats/after_merging_label_ids/ \
    --retriever_train_mode random --retriever_val_mode random \
    --retriever_ckpt analogical_within.pt \
    --lr 1e-4 --batch_size 8 --epochs 400 \
    --model multi_mem \
    --rotary_pe --pre_norm --feat_dim 264 \
    --negative_obj_weight 0.2 \
    --num_memories 5 --same_wild_augment_train \
    --train_split multicat12
